### ISSUE TITLE
responsive-images-css

### ISSUE THREAD

**Issue by wtser** [wtser/wtser.github.io#59]
https://css-tricks.com/responsive-images-css/?utm_source=html5weekly&utm_medium=email

**Comment by wtser** [comment]
html markup
---
```html
<img srcset="
  examples/images/image-384.jpg 1x, 
  examples/images/image-768.jpg 2x
" alt="…">
```

**Comment by wtser** [comment]
css
---
```css
.img {
  background-image: url(examples/images/image-384.jpg); 
}
@media 
  (-webkit-min-device-pixel-ratio: 2), 
  (min-resolution: 192dpi) { 
  .img {
    background-image: url(examples/images/image-768.jpg);
  }
}
```
